#!/usr/bin/env python3
"""Fail-closed TLS SNI relay for captive-portal Microsoft authentication.

This is NOT a general HTTP/HTTPS proxy.

The HP switch policy-routes only pre-registration TCP/443 packets to the portal
host.  A host firewall REDIRECTs those packets to this listener.  The listener
reads the TLS ClientHello, extracts SNI, and connects only to an explicit
Microsoft identity hostname allow-list.  It resolves the approved SNI itself;
the client's original destination IP is never used for the upstream socket.

Consequences:
  * raw-IP/no-SNI TLS is rejected;
  * CONNECT proxy requests cannot choose an arbitrary upstream destination;
  * DNS tricks on the client do not select the upstream destination;
  * non-allow-listed HTTPS remains unavailable before registration.

The source CIDR file is generated by hp5130-acl-baseline-preauth.sh so the
switch, host firewall and relay use the same definition of "pre-registration".
"""

from __future__ import annotations

import asyncio
import ipaddress
import logging
import os
import socket
import struct
from collections import defaultdict
from pathlib import Path
from typing import Iterable

LOG = logging.getLogger("preauth-sni-proxy")

LISTEN_HOST = os.getenv("PREAUTH_PROXY_LISTEN_HOST", "0.0.0.0")
LISTEN_PORT = int(os.getenv("PREAUTH_PROXY_PORT", "8443"))
SOURCE_CIDRS_FILE = os.getenv(
    "PREAUTH_SOURCE_CIDRS_FILE",
    "/scripts/scriptdata/preauth-source-cidrs.txt",
)
LOCAL_IPS_FILE = os.getenv(
    "PREAUTH_LOCAL_IPS_FILE",
    "/scripts/scriptdata/preauth-local-https-ips.txt",
)
HELLO_TIMEOUT = float(os.getenv("PREAUTH_HELLO_TIMEOUT", "10"))
CONNECT_TIMEOUT = float(os.getenv("PREAUTH_CONNECT_TIMEOUT", "10"))
IDLE_TIMEOUT = float(os.getenv("PREAUTH_IDLE_TIMEOUT", "120"))
MAX_HELLO_BYTES = int(os.getenv("PREAUTH_MAX_HELLO_BYTES", "65536"))
MAX_CONNECTIONS = int(os.getenv("PREAUTH_MAX_CONNECTIONS", "256"))
MAX_CONNECTIONS_PER_CLIENT = int(os.getenv("PREAUTH_MAX_CONNECTIONS_PER_CLIENT", "12"))

# Deliberately narrow.  These are Microsoft-owned identity/sign-in endpoints
# used by the device-login experience.  If Microsoft adds another dependency,
# add the exact hostname (or a Microsoft-controlled identity suffix) after
# confirming it in the relay's DENY-SNI log.  Do not add generic Azure/CDN
# suffixes or arbitrary *.microsoft.com.
DEFAULT_ALLOWED_SNI = """
microsoft.com
www.microsoft.com
login.microsoftonline.com
login.microsoft.com
login.windows.net
login.live.com
device.login.microsoftonline.com
ccs.login.microsoftonline.com
login.microsoftonline-p.com
account.activedirectory.windowsazure.com
accounts.accesscontrol.windows.net
autologon.microsoftazuread-sso.com
secure.aadcdn.microsoftonline-p.com
aadcdn.msauth.net
aadcdn.msauthimages.net
aadcdn.msftauth.net
aadcdn.msftauthimages.net
logincdn.msauth.net
logincdn.msftauth.net
*.msauth.net
*.msauthimages.net
*.msftauth.net
*.msftauthimages.net
*.phonefactor.net
""".split()


def _parse_patterns(raw: str | None) -> tuple[set[str], tuple[str, ...]]:
    values = DEFAULT_ALLOWED_SNI if not raw else [x.strip() for x in raw.replace(";", ",").split(",")]
    exact: set[str] = set()
    suffixes: set[str] = set()
    for item in values:
        item = (item or "").strip().lower().rstrip(".")
        if not item:
            continue
        if item.startswith("*."):
            suffixes.add(item[1:])  # store '.example.com'
        elif "*" in item:
            raise SystemExit(f"Unsupported PREAUTH_ALLOWED_SNI wildcard: {item!r}")
        else:
            exact.add(item)
    return exact, tuple(sorted(suffixes, key=len, reverse=True))


ALLOWED_EXACT, ALLOWED_SUFFIXES = _parse_patterns(os.getenv("PREAUTH_ALLOWED_SNI"))


def _normalise_hostname(host: str) -> str:
    host = (host or "").strip().lower().rstrip(".")
    if not host or len(host) > 253 or "\x00" in host:
        return ""
    try:
        # SNI is normally already ASCII; canonicalising prevents Unicode tricks.
        host = host.encode("idna").decode("ascii")
    except Exception:
        return ""
    labels = host.split(".")
    if any(not label or len(label) > 63 for label in labels):
        return ""
    return host


def host_allowed(host: str) -> bool:
    host = _normalise_hostname(host)
    if not host:
        return False
    if host in ALLOWED_EXACT:
        return True
    return any(host.endswith(suffix) and host != suffix[1:] for suffix in ALLOWED_SUFFIXES)


def _load_source_networks() -> tuple[ipaddress.IPv4Network, ...]:
    values: list[str] = []
    raw = (os.getenv("PREAUTH_SOURCE_CIDRS") or "").strip()
    if raw:
        values.extend(x.strip() for x in raw.replace(";", ",").split(",") if x.strip())

    path = Path(SOURCE_CIDRS_FILE)
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                values.append(line)

    if not values:
        # Unregistered wifi clients hold regular-pool IPs (ACL-blocked at the
        # uplink), so pre-auth sources cannot be narrowed to blocked-pool CIDRs
        # here. Default to the whole private client range for this site.
        network_word = (os.getenv("NETWORK_WORD") or "192.168").strip()
        values.append(f"{network_word}.0.0/16")

    nets: list[ipaddress.IPv4Network] = []
    for value in values:
        try:
            net = ipaddress.ip_network(value, strict=False)
        except ValueError as exc:
            raise SystemExit(f"Invalid pre-auth source CIDR {value!r}: {exc}") from exc
        if not isinstance(net, ipaddress.IPv4Network):
            raise SystemExit("This relay is IPv4-only; do not put IPv6 networks in PREAUTH_SOURCE_CIDRS")
        if net not in nets:
            nets.append(net)

    if not nets:
        raise SystemExit(
            "No pre-auth source CIDRs were loaded. Refusing to start fail-open. "
            "Run hp5130-acl-baseline-preauth.sh first or set PREAUTH_SOURCE_CIDRS."
        )
    return tuple(nets)


SOURCE_NETWORKS = _load_source_networks()


def _load_local_https_ips() -> frozenset[str]:
    values: list[str] = []
    raw = (os.getenv("PREAUTH_LOCAL_HTTPS_IPS") or "").strip()
    if raw:
        values.extend(x.strip() for x in raw.replace(";", ",").split(",") if x.strip())
    path = Path(LOCAL_IPS_FILE)
    if path.is_file():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                values.append(line)

    if not values:
        portal_ip = (os.getenv("PORTAL_IP") or "").strip()
        if portal_ip:
            values.append(portal_ip)

    result: set[str] = set()
    for value in values:
        try:
            ip = ipaddress.ip_address(value)
        except ValueError as exc:
            raise SystemExit(f"Invalid local HTTPS IP {value!r}: {exc}") from exc
        if not isinstance(ip, ipaddress.IPv4Address):
            raise SystemExit("PREAUTH_LOCAL_HTTPS_IPS currently supports IPv4 only")
        result.add(str(ip))
    if not result:
        raise SystemExit(
            "No local HTTPS IPs were loaded. Refusing to start because captive-portal HTTPS "
            "would be intercepted without a safe local pass-through destination."
        )
    return frozenset(result)


LOCAL_HTTPS_IPS = _load_local_https_ips()


def source_allowed(ip_text: str) -> bool:
    try:
        ip = ipaddress.ip_address(ip_text)
    except ValueError:
        return False
    return isinstance(ip, ipaddress.IPv4Address) and any(ip in net for net in SOURCE_NETWORKS)


class ClientHelloError(ValueError):
    pass


def _u16(data: bytes, pos: int) -> tuple[int, int]:
    if pos + 2 > len(data):
        raise ClientHelloError("truncated uint16")
    return int.from_bytes(data[pos:pos + 2], "big"), pos + 2


def extract_sni_from_client_hello(handshake: bytes) -> str:
    """Extract the first host_name SNI value from a complete ClientHello body."""
    p = 0
    if len(handshake) < 2 + 32 + 1:
        raise ClientHelloError("ClientHello too short")

    p += 2      # legacy_version
    p += 32     # random

    sid_len = handshake[p]
    p += 1
    p += sid_len
    if p > len(handshake):
        raise ClientHelloError("truncated session id")

    cipher_len, p = _u16(handshake, p)
    p += cipher_len
    if p >= len(handshake):
        raise ClientHelloError("truncated cipher suites")

    compression_len = handshake[p]
    p += 1 + compression_len
    if p > len(handshake):
        raise ClientHelloError("truncated compression methods")

    ext_total, p = _u16(handshake, p)
    ext_end = p + ext_total
    if ext_end > len(handshake):
        raise ClientHelloError("truncated extensions")

    while p + 4 <= ext_end:
        ext_type, p = _u16(handshake, p)
        ext_len, p = _u16(handshake, p)
        ext_data = handshake[p:p + ext_len]
        p += ext_len
        if len(ext_data) != ext_len:
            raise ClientHelloError("truncated extension")
        if ext_type != 0:  # server_name
            continue

        if len(ext_data) < 2:
            raise ClientHelloError("bad server_name extension")
        list_len = int.from_bytes(ext_data[:2], "big")
        q = 2
        end = min(len(ext_data), 2 + list_len)
        while q + 3 <= end:
            name_type = ext_data[q]
            name_len = int.from_bytes(ext_data[q + 1:q + 3], "big")
            q += 3
            name = ext_data[q:q + name_len]
            q += name_len
            if len(name) != name_len:
                raise ClientHelloError("truncated server_name")
            if name_type == 0:
                try:
                    return _normalise_hostname(name.decode("ascii", errors="strict"))
                except UnicodeDecodeError as exc:
                    raise ClientHelloError("non-ASCII SNI") from exc
        return ""

    return ""


async def read_client_hello(reader: asyncio.StreamReader) -> tuple[str, bytes]:
    """Read enough TLS handshake records to obtain one complete ClientHello."""
    raw = bytearray()
    handshake_bytes = bytearray()
    expected_handshake_size: int | None = None

    while len(raw) < MAX_HELLO_BYTES:
        header = await asyncio.wait_for(reader.readexactly(5), timeout=HELLO_TIMEOUT)
        content_type = header[0]
        record_len = int.from_bytes(header[3:5], "big")
        if record_len <= 0 or record_len > 18432:
            raise ClientHelloError(f"invalid TLS record length {record_len}")
        payload = await asyncio.wait_for(reader.readexactly(record_len), timeout=HELLO_TIMEOUT)
        raw += header + payload

        if content_type != 22:  # handshake
            raise ClientHelloError("first TLS flight is not a handshake record")
        handshake_bytes += payload

        if expected_handshake_size is None and len(handshake_bytes) >= 4:
            if handshake_bytes[0] != 1:  # ClientHello
                raise ClientHelloError("first handshake message is not ClientHello")
            body_len = int.from_bytes(handshake_bytes[1:4], "big")
            expected_handshake_size = 4 + body_len
            if expected_handshake_size > MAX_HELLO_BYTES:
                raise ClientHelloError("ClientHello exceeds configured maximum")

        if expected_handshake_size is not None and len(handshake_bytes) >= expected_handshake_size:
            body = bytes(handshake_bytes[4:expected_handshake_size])
            return extract_sni_from_client_hello(body), bytes(raw)

    raise ClientHelloError("ClientHello exceeds configured maximum")


SO_ORIGINAL_DST = 80  # Linux netfilter getsockopt(SOL_IP, SO_ORIGINAL_DST)


def original_destination(writer: asyncio.StreamWriter) -> tuple[str, int] | None:
    sock = writer.get_extra_info("socket")
    if sock is None:
        return None
    try:
        raw = sock.getsockopt(socket.SOL_IP, SO_ORIGINAL_DST, 16)
        if len(raw) < 8:
            return None
        port = struct.unpack_from("!H", raw, 2)[0]
        ip_text = socket.inet_ntoa(raw[4:8])
        return ip_text, port
    except OSError:
        return None


async def _resolve_public(host: str) -> list[str]:
    loop = asyncio.get_running_loop()
    infos = await loop.getaddrinfo(host, 443, type=socket.SOCK_STREAM)
    result: list[str] = []
    for family, _socktype, _proto, _canon, sockaddr in infos:
        if family not in (socket.AF_INET, socket.AF_INET6):
            continue
        ip_text = sockaddr[0]
        try:
            ip = ipaddress.ip_address(ip_text)
        except ValueError:
            continue
        # Never let an allow-listed DNS name turn this relay into an SSRF path
        # to RFC1918, loopback, link-local, multicast, etc.
        if not ip.is_global:
            LOG.warning("DENY-DNS host=%s resolved_non_global=%s", host, ip_text)
            continue
        if ip_text not in result:
            result.append(ip_text)
    return result


async def _open_upstream(host: str) -> tuple[asyncio.StreamReader, asyncio.StreamWriter]:
    addresses = await _resolve_public(host)
    if not addresses:
        raise OSError(f"no public addresses for {host}")

    last_exc: Exception | None = None
    for address in addresses:
        try:
            return await asyncio.wait_for(
                asyncio.open_connection(address, 443),
                timeout=CONNECT_TIMEOUT,
            )
        except Exception as exc:  # try next Microsoft address
            last_exc = exc
    raise OSError(f"could not connect to {host}: {last_exc}")


async def _open_local_https(ip_text: str, port: int) -> tuple[asyncio.StreamReader, asyncio.StreamWriter]:
    if ip_text not in LOCAL_HTTPS_IPS or port != 443:
        raise PermissionError(f"local destination {ip_text}:{port} is not allow-listed")
    return await asyncio.wait_for(
        asyncio.open_connection(ip_text, port),
        timeout=CONNECT_TIMEOUT,
    )


async def _pipe(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
    try:
        while True:
            chunk = await asyncio.wait_for(reader.read(65536), timeout=IDLE_TIMEOUT)
            if not chunk:
                break
            writer.write(chunk)
            await writer.drain()
    except (asyncio.TimeoutError, ConnectionError, OSError):
        pass
    finally:
        try:
            writer.write_eof()
        except (AttributeError, OSError, RuntimeError):
            pass


_semaphore = asyncio.Semaphore(MAX_CONNECTIONS)
_per_client: defaultdict[str, int] = defaultdict(int)


async def handle_client(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
    peer = writer.get_extra_info("peername")
    client_ip = str(peer[0]) if peer else ""

    if not source_allowed(client_ip):
        LOG.warning("DENY-SOURCE client=%s", client_ip or "unknown")
        writer.close()
        await writer.wait_closed()
        return

    if _per_client[client_ip] >= MAX_CONNECTIONS_PER_CLIENT:
        LOG.warning("DENY-LIMIT client=%s", client_ip)
        writer.close()
        await writer.wait_closed()
        return

    async with _semaphore:
        _per_client[client_ip] += 1
        upstream_writer: asyncio.StreamWriter | None = None
        try:
            orig = original_destination(writer)
            sni, first_flight = await read_client_hello(reader)

            if host_allowed(sni):
                # For an approved Microsoft hostname, deliberately ignore the
                # client's original destination (which may be wrong because of
                # captive DNS hijack) and resolve the approved SNI ourselves.
                LOG.info("ALLOW-MICROSOFT client=%s sni=%s original=%s", client_ip, sni, orig)
                upstream_reader, upstream_writer = await _open_upstream(sni)
            elif orig and orig[0] in LOCAL_HTTPS_IPS and orig[1] == 443:
                # Preserve access to the captive portal's own HTTPS listener.
                # This is destination-IP constrained and cannot become an
                # arbitrary internal-network relay.
                LOG.info("ALLOW-LOCAL client=%s sni=%r original=%s", client_ip, sni, orig)
                upstream_reader, upstream_writer = await _open_local_https(orig[0], orig[1])
            else:
                LOG.warning("DENY-SNI client=%s sni=%r original=%s", client_ip, sni, orig)
                return

            upstream_writer.write(first_flight)
            await upstream_writer.drain()

            t1 = asyncio.create_task(_pipe(reader, upstream_writer))
            t2 = asyncio.create_task(_pipe(upstream_reader, writer))
            done, pending = await asyncio.wait({t1, t2}, return_when=asyncio.FIRST_COMPLETED)
            for task in pending:
                task.cancel()
            await asyncio.gather(*pending, return_exceptions=True)
            await asyncio.gather(*done, return_exceptions=True)
        except (asyncio.IncompleteReadError, asyncio.TimeoutError, ClientHelloError) as exc:
            LOG.warning("DENY-TLS client=%s reason=%s", client_ip, exc)
        except Exception as exc:
            LOG.warning("RELAY-ERROR client=%s reason=%s", client_ip, exc)
        finally:
            _per_client[client_ip] -= 1
            if _per_client[client_ip] <= 0:
                _per_client.pop(client_ip, None)
            if upstream_writer is not None:
                upstream_writer.close()
                try:
                    await upstream_writer.wait_closed()
                except Exception:
                    pass
            writer.close()
            try:
                await writer.wait_closed()
            except Exception:
                pass


async def main() -> None:
    logging.basicConfig(
        level=getattr(logging, os.getenv("PREAUTH_PROXY_LOG_LEVEL", "INFO").upper(), logging.INFO),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    LOG.info("source networks: %s", ", ".join(map(str, SOURCE_NETWORKS)))
    LOG.info("local HTTPS IPs: %s", ", ".join(sorted(LOCAL_HTTPS_IPS)))
    LOG.info(
        "allowed SNI: exact=%s suffixes=%s",
        ",".join(sorted(ALLOWED_EXACT)),
        ",".join(ALLOWED_SUFFIXES),
    )
    server = await asyncio.start_server(handle_client, LISTEN_HOST, LISTEN_PORT)
    sockets = ", ".join(str(sock.getsockname()) for sock in (server.sockets or []))
    LOG.info("listening on %s", sockets)
    async with server:
        await server.serve_forever()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
